export default {
  login: 'Mahmud1087',
  id: 106757413,
  node_id: 'U_kgDOBlz9JQ',
  avatar_url: 'https://avatars.githubusercontent.com/u/106757413?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/Mahmud1087',
  html_url: 'https://github.com/Mahmud1087',
  followers_url: 'https://api.github.com/users/Mahmud1087/followers',
  following_url:
    'https://api.github.com/users/Mahmud1087/following{/other_user}',
  gists_url: 'https://api.github.com/users/Mahmud1087/gists{/gist_id}',
  starred_url: 'https://api.github.com/users/Mahmud1087/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/Mahmud1087/subscriptions',
  organizations_url: 'https://api.github.com/users/Mahmud1087/orgs',
  repos_url: 'https://api.github.com/users/Mahmud1087/repos',
  events_url: 'https://api.github.com/users/Mahmud1087/events{/privacy}',
  received_events_url:
    'https://api.github.com/users/Mahmud1087/received_events',
  type: 'User',
  site_admin: false,
  name: 'Mahmud Enesi Abdulazeez',
  company: null,
  blog: '',
  location: 'Kogi, Nigeria',
  email: null,
  hireable: null,
  bio: 'Your frontend dev guy',
  twitter_username: 'MahmudEnesi',
  public_repos: 32,
  public_gists: 0,
  followers: 61,
  following: 56,
  created_at: '2022-06-02T14:33:00Z',
  updated_at: '2023-01-01T15:30:15Z',
}
